### ISSUE TITLE
Docker image missing?

### ISSUE THREAD

**Issue by yang** [looorent/notion-exporter#1]
Thanks for putting this up! The docker image cited in the README doesn't seem to be there (`looorent/notion-exporter:latest`). Would you mind pushing it and/or add the Dockerfile? Thanks!

**Comment by looorent** [comment]
Hi @yang ,

The docker image is built through a Gradle plugin. The Docker images are present in the folder `src/main/docker`.

The image was not public on Docker Hub, indeed. It is now ok: https://hub.docker.com/r/looorent/notion-exporter
